# -*- coding: utf-8 -*-
"""SM LAST LAB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGieeheTp7QUYZlLLj_FEyEu1HMmzD0f
"""

import pandas as pd
import numpy as np
df=pd.read_csv("HousingData.csv")
df

df.head()

df.describe()

df.info()

df.isnull().sum()

df["CRIM"].fillna(dataset["CRIM"].median(),inplace=True)
df["CHAS"].fillna(dataset["CHAS"].mean(),inplace=True)
df["ZN"].fillna(dataset["ZN"].mean(),inplace=True)
df["INDUS"].fillna(dataset["INDUS"].median(),inplace=True)
df["AGE"].fillna(dataset["AGE"].median(),inplace=True)
df["LSTAT"].fillna(dataset["LSTAT"].mean(),inplace=True)

df.isnull().sum()

df=df.dropna()

X=df.iloc[:,1:]
y=df.iloc[:,0]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

from sklearn.linear_model import LinearRegression
ml = LinearRegression()
ml.fit(X_train,y_train)

Y_pred=ml.predict(X_test)
Y_pred=pd.DataFrame(Y_pred,columns=["Predicted"])
Y_pred

from sklearn.metrics import r2_score
print("acuuracy",r2_score(y_test,Y_pred))

feature engineering 
outliers
column remove, transform